title: Rajat Parashar
email: ''
description: >-
  This is Rajat Parashar's personal blog. Here I throw crap out of my mind. You
  may find this crap useful.
baseurl: /
url: https://parasharrajat.github.io
twitter_username: '_rajat_parashar'
github_username: parasharrajat
facebook_username: rajat47hitman
linkedin_username: rajatparashar47
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-admin

exclude:
  - vendor
  - .bundle

header_pages:
  - title: Posts
    url: /


paginate: 2
paginate_path: "page:num/"
