title: Coder Steps
email: ''
description: >-
  This is Rajat Parashar's personal blog. Here I throw crap out of my mind. You
  may find this crap useful.
baseurl: /
url: codersteps.com
twitter_username: '@_rajat_parashar'
github_username: parasharrajat
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-admin

exclude:
  - vender
  - .bundle

header_pages:
  - title: Posts
    url: /index.html

  - title: Social
    url: /social.html

  - title: About
    url: /about.html
